image: rust:1.52

cache:
  paths:
    - target/*

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo run -- -d helloworld.bf

# vim: ts=2 sts=2 sw=2 expandtab
